Assets/Scripts/Editor/SimpleBuild/BuildAssetBundle.cs
Assets/Scripts/Editor/SimpleBuild/BuildAssetBundle.cs.meta

* AssetBundle をビルドするためのクラスを追加しました。
* Jenkins 向けの公開メソッドも実装しています。
* 現在の所、出力先は Assets/AssetBundles/ 以下に固定しています。

AssetBundle ビルドをサポートします

---

Assets/Scripts/Editor/SimpleBuild/BuildAssetBundle.cs
Assets/Scripts/Editor/SimpleBuild/BuildPlayer.cs

* メニューの階層を一段深く掘ります。
* 直下のメニューが多くなると視認性が悪くなると判断しました。

メニューの階層を変更します

---

Assets/Scripts/Editor/SimpleBuild/BuildPlayer.cs
package-lock.json
package.json

* 引数の名称は一旦 `development_build` で固定しています。

開発ビルドをサポート

---

Assets/Scripts/Editor/SimpleBuild/BuildAssetBundle.cs

* Standalone 向けの AssetBundle もビルド可能にします。

Support Standalone build

---

Assets/Scripts/Editor/SimpleBuild/BuildPlayer.cs

* http://tsubakit1.hateblo.jp/entry/2017/03/22/233000 を参考

:sparkles: Support resource compression with LZ4

---

Assets/Scripts/Editor/SimpleBuild/BuildPlayer.cs
package-lock.json
package.json

* 将来的に Cloud Build を利用する場合にも対応できる

CI ツールなどから貰う値を引数から環境変数に変更

---

Assets/Scripts/Editor/SimpleBuild/BuildAssetBundle.cs
Assets/Tests/Scripts/Editor/SimpleBuild/BuildAssetBundleTest.cs

* UnityEditor.Build.IPostprocessBuild.OnPostprocessBuild などのメソッドインタフェースに揃えます

コールバックのメソッドインタフェースを Unity 側に揃える

---

Assets/Scripts/Editor/SimpleBuild/BuildAssetBundle.cs
Assets/Scripts/Editor/SimpleBuild/BuildPlayer.cs

* `@umm/xcode_archiver` などで `EditorUserBuildSettings.development` を見るので処理を変更

EditorUserBuildSettings.development を操作する

---

Assets/Scripts/Editor/SimpleBuild/BuildAssetBundle.cs

* 処理順の問題で IPostprocessBuildAssetBundle が呼ばれなかったため修正

PostprocessBuildAssetBundle が呼ばれない問題を修正

---

Assets/Editor/Scripts/SimpleBuild/BuildAssetBundle.cs

Assembly ファイルを検索出来るようにする

---

Assets/Editor/Scripts/SimpleBuild/BuildAssetBundle.cs
Assets/Editor/Scripts/SimpleBuild/BuildPlayer.cs

* Accept operation by environment variable

Support environment variables

---

Assets/Editor/Scripts/SimpleBuild/BuildAssetBundle.cs
Assets/Editor/Scripts/SimpleBuild/BuildOptions.meta
Assets/Editor/Scripts/SimpleBuild/BuildOptions/AssetBundle.cs
Assets/Editor/Scripts/SimpleBuild/BuildOptions/AssetBundle.cs.meta
Assets/Editor/Scripts/SimpleBuild/BuildPlayer.cs
ProjectSettings/EditorSettings.asset

* Implement `Project > AssetBundle > Options > Force Rebuild` menu

Implement Force Rebuild option for AssetBundle

---

Assets/Editor/Scripts/SimpleBuild/BuildPlayer.cs

* Split directory by environement (development/production)
* I wanted to remove solid writing

Change directory path to export

---

Assets/Editor/Scripts/SimpleBuild/BuildPlayer.cs

Change default setting of allow debugging #38

---

ProjectSettings/ProjectSettings.asset

Use .NET 4.x

---

.gitignore
Assets/Editor/Scripts/SimpleBuild/BuildPlayer.cs
Packages/manifest.json
ProjectSettings/VFXManager.asset

* Change flag name to `BUILD_FASTER` instead of `BUILD_CLEAN` to put to `@umm/xcode_archiver`

Change flag name

---

Assets/Editor/Scripts/SimpleBuild/BuildPlayer.cs

* Avoid stripping Java class referenced from `AndroidJavaClass/AndroidJavaObject`

Disable minify for Android

---

Assets/Editor/Scripts/SimpleBuild/BuildPlayer.cs

* Use proguard-user.txt if need to keep classes

Use ProGuard

---

Assets/Editor/Scripts/SimpleBuild/BuildPlayer.cs

* Use environment variables listed below
* `BUILD_ANDROID_SDK_PATH`
* `BUILD_ANDROID_NDK_PATH`
* `BUILD_JDK_PATH`

Set Android SDK/NDK, JDK path from environment variables

---

Assets/Editor/Scripts/SimpleBuild/BuildPlayer.cs

Android の minify 関連オプションを削除

---

Assets/Editor/Scripts/SimpleBuild/BuildPlayer.cs

https://github.com/umm/simple_build/pull/59 で話した結果 `AcceptExternalModificationsToPlayer` を設定している部分を丸っと消すことにした

Remove AcceptExternalModificationsToPlayer option for iOS build
